// Demo catalog for Vaani Shop. Every product is local data — no network needed.
// `tags` carries both English and Hindi words so search works on either script.
(function () {
  const CATEGORIES = [
    { id: "saree", name: "साड़ी", en: "Sarees", emoji: "🥻", hue: 330 },
    { id: "kurti", name: "कुर्ती", en: "Kurtis", emoji: "👗", hue: 290 },
    { id: "men", name: "पुरुष", en: "Men", emoji: "👕", hue: 210 },
    { id: "footwear", name: "जूते-चप्पल", en: "Footwear", emoji: "👟", hue: 25 },
    { id: "jewellery", name: "ज्वेलरी", en: "Jewellery", emoji: "💍", hue: 45 },
    { id: "kitchen", name: "किचन", en: "Kitchen", emoji: "🍳", hue: 15 },
    { id: "home", name: "घर सजावट", en: "Home Decor", emoji: "🪔", hue: 160 },
    { id: "beauty", name: "ब्यूटी", en: "Beauty", emoji: "💄", hue: 345 },
    { id: "kids", name: "बच्चे", en: "Kids", emoji: "🧸", hue: 190 },
    { id: "mobile", name: "मोबाइल एक्सेसरीज़", en: "Mobile Accessories", emoji: "🎧", hue: 250 },
  ];

  const APPAREL = ["S", "M", "L", "XL", "XXL"];
  const FREE = ["Free Size"];

  // [id, cat, hindi name, english name, price, mrp, rating, ratingCount, emoji, hue,
  //  sizes, colors, material, desc, highlights[], tags, deliveryDays]
  const RAW = [
    ["p01", "saree", "बनारसी सिल्क साड़ी", "Banarasi Silk Saree", 899, 2499, 4.4, 12840, "🥻", 340, FREE, ["लाल", "मैरून", "हरा"], "आर्ट सिल्क",
      "ज़री के बॉर्डर वाली बनारसी स्टाइल साड़ी, साथ में ब्लाउज़ पीस। शादी और त्योहार के लिए बढ़िया।",
      ["ब्लाउज़ पीस साथ में", "ज़री बॉर्डर", "5.5 मीटर लंबी"], "banarasi silk saree wedding shaadi tyohar festival red laal party", 5],
    ["p02", "saree", "कॉटन प्रिंटेड साड़ी", "Cotton Printed Saree", 449, 999, 4.1, 8420, "🥻", 200, FREE, ["नीला", "पीला", "गुलाबी"], "कॉटन",
      "हल्की, हवादार कॉटन साड़ी, रोज़ पहनने और ऑफ़िस के लिए आरामदायक।",
      ["रोज़ पहनने लायक", "हाथ से धो सकते हैं", "ब्लाउज़ पीस साथ में"], "cotton saree daily office casual blue neela summer garmi", 4],
    ["p03", "saree", "जॉर्जेट पार्टी साड़ी", "Georgette Party Saree", 649, 1799, 4.3, 5210, "🥻", 280, FREE, ["बैंगनी", "काला", "गुलाबी"], "जॉर्जेट",
      "सीक्विन वर्क वाली हल्की जॉर्जेट साड़ी, पार्टी और संगीत के लिए।",
      ["सीक्विन वर्क", "हल्की और फ्लोई", "ब्लाउज़ पीस साथ में"], "georgette party saree sequin sangeet black purple", 5],
    ["p04", "saree", "शिफॉन फ्लोरल साड़ी", "Chiffon Floral Saree", 379, 899, 3.9, 3120, "🥻", 120, FREE, ["हरा", "आसमानी"], "शिफॉन",
      "फूलों वाले प्रिंट की सस्ती और सुंदर शिफॉन साड़ी।",
      ["फ्लोरल प्रिंट", "बजट में", "हल्की"], "chiffon floral saree budget sasti flowers green", 4],

    ["p05", "kurti", "अनारकली कुर्ती", "Anarkali Kurti", 549, 1499, 4.3, 18230, "👗", 300, APPAREL, ["गुलाबी", "नीला", "पीला"], "रेयॉन",
      "घेरदार अनारकली कुर्ती, गोटा पट्टी के काम के साथ। त्योहार और फंक्शन के लिए।",
      ["फ्लेयर्ड घेर", "गोटा पट्टी वर्क", "घुटने से नीचे लंबाई"], "anarkali kurti festival function pink flared ethnic", 4],
    ["p06", "kurti", "कॉटन स्ट्रेट कुर्ती", "Cotton Straight Kurti", 329, 799, 4.2, 25110, "👗", 180, APPAREL, ["सफ़ेद", "नीला", "हरा"], "कॉटन",
      "रोज़ पहनने के लिए सीधी कॉटन कुर्ती, ब्लॉक प्रिंट के साथ।",
      ["ब्लॉक प्रिंट", "साइड पॉकेट", "मशीन वॉश"], "cotton kurti straight daily office white block print sasti", 4],
    ["p07", "kurti", "कुर्ती पैंट दुपट्टा सेट", "Kurta Pant Dupatta Set", 799, 2199, 4.5, 9640, "👗", 350, APPAREL, ["मैरून", "हरा", "नीला"], "रेयॉन ब्लेंड",
      "पूरा तीन पीस सेट — कुर्ती, पैंट और दुपट्टा। गिफ़्ट के लिए भी अच्छा।",
      ["3 पीस सेट", "कढ़ाई वाला योक", "दुपट्टा साथ में"], "kurta set suit dupatta three piece gift ethnic salwar", 5],
    ["p08", "kurti", "शॉर्ट टॉप कुर्ती", "Short Kurti Top", 249, 599, 3.8, 6430, "👗", 30, ["S", "M", "L", "XL"], ["पीला", "काला"], "क्रेप",
      "जीन्स के साथ पहनने वाली छोटी कुर्ती, कॉलेज के लिए बढ़िया।",
      ["जीन्स के साथ", "हल्का कपड़ा", "बजट में"], "short kurti top jeans college casual yellow", 4],

    ["p09", "men", "पुरुषों की कॉटन शर्ट", "Men's Cotton Shirt", 399, 999, 4.2, 21400, "👕", 215, ["M", "L", "XL", "XXL"], ["सफ़ेद", "आसमानी", "काला"], "कॉटन",
      "फ़ॉर्मल और कैज़ुअल दोनों में चलने वाली कॉटन शर्ट।",
      ["रेगुलर फ़िट", "फुल स्लीव", "ऑफ़िस के लिए"], "men shirt cotton formal office white mard aadmi", 4],
    ["p10", "men", "पुरुषों का कुर्ता पायजामा", "Men's Kurta Pyjama", 599, 1599, 4.4, 11250, "🧥", 40, ["M", "L", "XL", "XXL"], ["क्रीम", "पीला", "मैरून"], "कॉटन सिल्क",
      "त्योहार और पूजा के लिए कुर्ता पायजामा सेट।",
      ["कुर्ता + पायजामा", "त्योहार के लिए", "हल्की चमक"], "men kurta pyjama festival puja diwali ethnic mard", 5],
    ["p11", "men", "पुरुषों की जीन्स", "Men's Jeans", 649, 1699, 4.1, 15600, "👖", 225, ["30", "32", "34", "36"], ["गहरा नीला", "काला"], "डेनिम",
      "स्ट्रेचेबल स्लिम फ़िट जीन्स, रोज़ाना पहनने के लिए।",
      ["स्ट्रेचेबल", "स्लिम फ़िट", "5 पॉकेट"], "men jeans denim slim blue black pant", 5],
    ["p12", "men", "पुरुषों की टी-शर्ट (3 का पैक)", "Men's T-shirt Pack of 3", 499, 1299, 4.0, 19870, "👕", 0, ["M", "L", "XL", "XXL"], ["मिक्स"], "कॉटन",
      "तीन सादी टी-शर्ट का पैक, घर और बाहर दोनों के लिए।",
      ["3 का पैक", "राउंड नेक", "सॉफ़्ट कॉटन"], "men tshirt t-shirt pack combo cotton round neck", 4],

    ["p13", "footwear", "महिलाओं की जूती", "Women's Juttis", 349, 899, 4.2, 7340, "🥿", 20, ["5", "6", "7", "8"], ["सुनहरा", "लाल"], "सिंथेटिक",
      "कढ़ाई वाली पंजाबी जूती, एथनिक कपड़ों के साथ।",
      ["कढ़ाई वाली", "मुलायम तला", "एथनिक लुक"], "jutti juttis women footwear ethnic punjabi chappal", 5],
    ["p14", "footwear", "पुरुषों के स्पोर्ट्स शूज़", "Men's Sports Shoes", 699, 1999, 4.1, 22100, "👟", 200, ["7", "8", "9", "10"], ["काला", "ग्रे", "नीला"], "मेश",
      "हल्के और आरामदायक रनिंग शूज़, सुबह की सैर के लिए।",
      ["हल्के", "एयर मेश", "मज़बूत तला"], "sports shoes running walking men joote sneakers", 5],
    ["p15", "footwear", "महिलाओं की चप्पल", "Women's Flat Slippers", 199, 499, 3.9, 30500, "🩴", 330, ["5", "6", "7", "8"], ["गुलाबी", "काला"], "EVA",
      "रोज़ पहनने वाली हल्की चप्पल।",
      ["हल्की", "फिसलन रोधी", "बजट में"], "chappal slipper women daily flats sasti", 4],

    ["p16", "jewellery", "कुंदन चोकर सेट", "Kundan Choker Set", 499, 1999, 4.3, 9870, "💎", 48, FREE, ["सुनहरा"], "मिश्र धातु",
      "झुमकों के साथ कुंदन चोकर हार, शादी और त्योहार के लिए।",
      ["झुमके साथ में", "गोल्ड प्लेटेड", "हल्का वज़न"], "kundan choker necklace set jewellery wedding haar jhumka", 5],
    ["p17", "jewellery", "ऑक्सीडाइज़्ड झुमके", "Oxidised Jhumkas", 149, 499, 4.2, 26700, "📿", 220, FREE, ["चांदी जैसा"], "ऑक्सीडाइज़्ड मेटल",
      "रोज़ पहनने वाले ऑक्सीडाइज़्ड झुमके, कुर्ती के साथ जंचते हैं।",
      ["हल्के", "त्वचा के लिए सुरक्षित", "बजट में"], "jhumka jhumke earrings oxidised silver kaan jewellery", 4],
    ["p18", "jewellery", "चूड़ियों का सेट", "Bangle Set", 199, 599, 4.0, 14300, "💍", 0, ["2.4", "2.6", "2.8"], ["लाल", "हरा", "सुनहरा"], "कांच और मेटल",
      "24 चूड़ियों का रंगीन सेट, करवा चौथ और तीज के लिए।",
      ["24 चूड़ियां", "चमकदार", "त्योहार स्पेशल"], "bangles choodi chudi set karwa chauth teej red", 5],

    ["p19", "kitchen", "नॉन-स्टिक कड़ाही", "Non-stick Kadhai", 549, 1299, 4.2, 11200, "🍳", 10, ["2 लीटर", "3 लीटर"], ["काला"], "एल्युमिनियम",
      "ढक्कन वाली नॉन-स्टिक कड़ाही, कम तेल में खाना।",
      ["कांच का ढक्कन", "इंडक्शन पर चलती है", "कम तेल"], "kadhai kadai non stick kitchen cooking pan tawa", 5],
    ["p20", "kitchen", "स्टील डिनर सेट (24 पीस)", "Steel Dinner Set 24 pcs", 1199, 2999, 4.4, 6210, "🍽️", 200, FREE, ["स्टील"], "स्टेनलेस स्टील",
      "6 लोगों के लिए 24 पीस स्टेनलेस स्टील डिनर सेट।",
      ["24 पीस", "जंग-रोधी", "गिफ़्ट के लिए बढ़िया"], "dinner set steel thali bartan plates kitchen gift", 6],
    ["p21", "kitchen", "प्रेशर कुकर 3 लीटर", "Pressure Cooker 3L", 899, 1899, 4.3, 17800, "🥘", 30, ["3 लीटर", "5 लीटर"], ["स्टील"], "एल्युमिनियम",
      "ISI मार्क वाला प्रेशर कुकर, गैस और इंडक्शन दोनों पर।",
      ["ISI मार्क", "इंडक्शन बेस", "5 साल वारंटी"], "pressure cooker kitchen cooking dal rice", 5],
    ["p22", "kitchen", "मसाला डिब्बा", "Masala Box", 299, 699, 4.5, 8800, "🫙", 40, FREE, ["स्टील"], "स्टेनलेस स्टील",
      "7 कटोरियों वाला स्टील मसाला डिब्बा, चम्मच के साथ।",
      ["7 कटोरियां", "कसा हुआ ढक्कन", "चम्मच साथ में"], "masala dabba box spice kitchen steel", 4],

    ["p23", "home", "LED दीया सेट (12 पीस)", "LED Diya Set 12 pcs", 249, 699, 4.1, 13400, "🪔", 40, FREE, ["सुनहरा"], "प्लास्टिक",
      "बिना तेल वाले LED दीये, दिवाली की सजावट के लिए। पानी में डालते ही जलते हैं।",
      ["पानी से जलने वाले", "12 पीस", "सुरक्षित"], "diya diye led diwali decoration lights deepak", 4],
    ["p24", "home", "कॉटन बेडशीट डबल", "Cotton Double Bedsheet", 599, 1499, 4.2, 20500, "🛏️", 200, ["डबल"], ["नीला", "गुलाबी", "हरा"], "कॉटन",
      "दो तकिया कवर के साथ डबल बेडशीट, जयपुरी प्रिंट।",
      ["2 तकिया कवर", "जयपुरी प्रिंट", "रंग पक्का"], "bedsheet chadar double bed cotton jaipuri pillow", 5],
    ["p25", "home", "तोरण / बंदनवार", "Door Toran", 199, 499, 4.0, 5600, "🎊", 50, FREE, ["रंगीन"], "कपड़ा और मोती",
      "दरवाज़े के लिए रंगीन तोरण, त्योहार और गृह प्रवेश के लिए।",
      ["मोती और गोटा", "1 मीटर", "त्योहार स्पेशल"], "toran bandarwar door decoration festival diwali griha pravesh", 4],
    ["p26", "home", "वॉल क्लॉक", "Wall Clock", 449, 1199, 4.1, 4300, "🕰️", 260, FREE, ["काला", "सुनहरा"], "MDF",
      "बिना आवाज़ वाली दीवार घड़ी, लिविंग रूम के लिए।",
      ["साइलेंट मूवमेंट", "12 इंच", "बैटरी साथ में"], "wall clock ghadi home decor living room", 5],

    ["p27", "beauty", "मैट लिपस्टिक सेट (4)", "Matte Lipstick Set of 4", 299, 899, 4.0, 16700, "💄", 345, FREE, ["मिक्स"], "—",
      "चार शेड वाला लंबे समय तक टिकने वाला मैट लिपस्टिक सेट।",
      ["4 शेड", "लंबे समय तक टिके", "हल्का"], "lipstick matte makeup beauty set lips", 4],
    ["p28", "beauty", "एलोवेरा जेल", "Aloe Vera Gel", 149, 299, 4.3, 32100, "🌿", 120, ["200 ml", "400 ml"], ["—"], "—",
      "त्वचा और बालों के लिए शुद्ध एलोवेरा जेल।",
      ["त्वचा और बाल दोनों", "बिना खुशबू", "सभी स्किन टाइप"], "aloe vera gel skin hair beauty skincare", 4],
    ["p29", "beauty", "हेयर ड्रायर", "Hair Dryer", 549, 1299, 3.9, 7800, "💨", 300, FREE, ["गुलाबी", "काला"], "प्लास्टिक",
      "1200W फोल्डेबल हेयर ड्रायर, गरम और ठंडी हवा।",
      ["1200 वाट", "फोल्डेबल", "2 स्पीड"], "hair dryer beauty baal", 5],

    ["p30", "kids", "बच्चों का कॉटन ड्रेस सेट", "Kids Cotton Dress Set", 349, 899, 4.3, 9100, "🧒", 180, ["1-2 साल", "2-3 साल", "3-4 साल", "4-5 साल"], ["पीला", "नीला"], "कॉटन",
      "बच्चों के लिए मुलायम कॉटन टी-शर्ट और शॉर्ट्स सेट।",
      ["मुलायम कॉटन", "2 पीस", "मशीन वॉश"], "kids baby dress set bachche cotton boys girls", 4],
    ["p31", "kids", "बच्चों का एथनिक लहंगा", "Kids Lehenga Choli", 599, 1499, 4.4, 4200, "👧", 330, ["2-3 साल", "4-5 साल", "6-7 साल"], ["गुलाबी", "लाल"], "सिल्क ब्लेंड",
      "छोटी बच्चियों के लिए त्योहार वाला लहंगा चोली।",
      ["दुपट्टा साथ में", "मुलायम अस्तर", "त्योहार स्पेशल"], "kids lehenga choli girls festival bachchi ethnic", 5],
    ["p32", "kids", "सॉफ़्ट टेडी बियर", "Soft Teddy Bear", 299, 799, 4.5, 11800, "🧸", 20, ["1 फुट", "2 फुट"], ["भूरा", "गुलाबी"], "प्लश",
      "मुलायम टेडी बियर, बच्चों के तोहफ़े के लिए।",
      ["बहुत मुलायम", "धो सकते हैं", "गिफ़्ट के लिए"], "teddy bear soft toy kids gift khilona birthday", 4],

    ["p33", "mobile", "वायरलेस ईयरबड्स", "Wireless Earbuds", 799, 2999, 4.0, 28400, "🎧", 250, FREE, ["काला", "सफ़ेद"], "—",
      "ब्लूटूथ ईयरबड्स, 20 घंटे का प्लेबैक, कॉलिंग के लिए माइक।",
      ["20 घंटे बैटरी", "टाइप-C चार्जिंग", "कॉलिंग माइक"], "earbuds earphones bluetooth wireless headphones mobile", 5],
    ["p34", "mobile", "10000mAh पावर बैंक", "10000mAh Power Bank", 699, 1499, 4.2, 19200, "🔋", 140, FREE, ["काला", "सफ़ेद"], "—",
      "फ़ास्ट चार्जिंग पावर बैंक, दो फ़ोन एक साथ चार्ज।",
      ["फ़ास्ट चार्जिंग", "2 USB पोर्ट", "हल्का"], "power bank charger mobile battery", 5],
    ["p35", "mobile", "मोबाइल स्टैंड", "Mobile Stand", 149, 399, 4.1, 9900, "📱", 230, FREE, ["काला", "सफ़ेद"], "ABS प्लास्टिक",
      "फोल्ड होने वाला मोबाइल स्टैंड, वीडियो कॉल और रील्स के लिए।",
      ["एडजस्टेबल", "फोल्डेबल", "हर फ़ोन पर"], "mobile stand holder phone video call", 4],
    ["p36", "mobile", "स्मार्ट वॉच", "Smart Watch", 1299, 3999, 4.0, 14500, "⌚", 200, FREE, ["काला", "गुलाबी"], "—",
      "कॉलिंग वाली स्मार्ट वॉच, हार्ट रेट और स्टेप काउंटर के साथ।",
      ["ब्लूटूथ कॉलिंग", "7 दिन बैटरी", "हार्ट रेट"], "smart watch ghadi fitness calling", 6],
  ];

  const PRODUCTS = RAW.map((r) => ({
    id: r[0], cat: r[1], name: r[2], en: r[3], price: r[4], mrp: r[5],
    rating: r[6], ratings: r[7], emoji: r[8], hue: r[9], sizes: r[10], colors: r[11],
    material: r[12], desc: r[13], highlights: r[14], tags: r[15], deliveryDays: r[16],
    seller: ["जयपुर क्राफ़्ट्स", "सूरत फ़ैब्रिक्स", "दिल्ली बाज़ार", "राजकोट होम", "लुधियाना निट्स"][parseInt(r[0].slice(1), 10) % 5],
    returnDays: r[1] === "beauty" ? 0 : 7,
  }));

  const COUPONS = {
    VAANI50: { code: "VAANI50", desc: "299 रुपये से ऊपर के ऑर्डर पर 50 रुपये की छूट", min: 299, flat: 50 },
    PEHLA10: { code: "PEHLA10", desc: "10% छूट, ज़्यादा से ज़्यादा 100 रुपये", min: 0, pct: 10, cap: 100 },
    TYOHAR100: { code: "TYOHAR100", desc: "999 रुपये से ऊपर के ऑर्डर पर 100 रुपये की छूट", min: 999, flat: 100 },
  };

  window.CATALOG = { CATEGORIES, PRODUCTS, COUPONS };
})();
